{% set name = "pyramid_mako" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0066c863441f1c3ddea60cee1ccc50d00a91a317a8052ca44131da1a12a840e2

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - mako >=1.1.0
    - pyramid

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyramid_mako

about:
  home: https://trypyramid.com
  license: LicenseRef-Pylons
  license_family: BSD
  license_file: LICENSE.txt
  summary: The Pyramid Web Framework, a Pylons project
  doc_url: https://docs.pylonsproject.org/projects/pyramid_mako/en/latest/
  dev_url: https://github.com/Pylons/pyramid_mako

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
    - JamesMakela-NOAA
